### ISSUE TITLE
Problems running SSG_LUGIA

### ISSUE THREAD

**Issue by Fgontr** [nibtehaz/SSG-LUGIA#1]
Hello! Thank you for your software and for the time it took you to answer this.
Try to download from the repository and after installing the requirements I activate Python3 and use

from main import SSG_LUGIA

and enter the command

>>> SSG_LUGIA('/My_sequence_path/='file.fasta' ,model_name='SSG_LUGIA-F')
   File "<stdin>", line 1
     SSG_LUGIA('/My_sequence_path/='file.fasta' ,model_name='SSG_LUGIA-F')
                                                                           ^
SyntaxError: invalid syntax 

I don't know much about programming, I'm trying to learn and I would appreciate your help infinitely

**Comment by nibtehaz** [comment]
Hi, thank you so much for your interest in our project.

It appears that you have issues with closing ' marks. It should be like this

SSG_LUGIA('/My_sequence_path/file.fasta' ,model_name='SSG_LUGIA-F')

Given that your fasta file is saved in '/My_sequence_path/file.fasta'

**Comment by Fgontr** [comment]
Hi! 
You are right. It was my mistake.

Thanks!
